### ISSUE TITLE
Dica de estruturas

### ISSUE THREAD

**Issue by lucaswilker14** [joaolcaas/p3-backend-project#6]
E ai João, tranquilo ?

Dei uma olhada no teu projeto e queria te dar uma dica pra modularizar e deixar umas estrutura mais legal e "componetizavél".

Tenta dar uma olhada nesse link: https://blog.risingstack.com/node-hero-node-js-project-structure-tutorial/

Abraço.

**Comment by joaolcaas** [comment]
Fala, vei! @lucaswilker14 

Tinha uma pasta "modelos" do lado de fora do src, mas não era para estar lá. Vi o link e acho que, pelo que entendi, ficou de acordo.
Qualquer coisa pode falar!
abs
